Repository he4rt/scylladb-php-driver, pull requests merged in 2023-03, with the labels that each got.

#48 Setup Github Actions as CI server
  .github/workflows/build.yml
  .github/workflows/test.yml
  .github/workflows/tests.yml
  Dockerfile
  composer.lock
Labels: enhancement

#49 feat: migrating tests to PestPHP
  tests-old/features/batch_statements.feature
  tests-old/features/duration.feature
  tests-old/features/duration_collections.feature
  tests-old/features/risky/function_and_aggregate_metadata.feature
  tests-old/features/simple_statements.feature
  tests-old/features/simple_string_queries.feature
  tests/Feature/Collections/CollectionsTest.php
  tests/Feature/Duration/DurationCollectionsTest.php
  tests/Feature/Duration/DurationTest.php
  tests/Feature/FunctionAggregatesMetadataTest.php
  tests/Feature/Statements/BatchStatementsTest.php
  tests/Feature/Statements/SimpleStatementsTest.php
  tests/Feature/Statements/SimpleStringQueriesTest.php
Labels: enhancement, good first issue

#55 feat: Using Cassandra user defined types from schema metadata test
  tests-old/features/user_defined_types.feature
  tests/Feature/DefinedTypes/UserDefinedTypesTest.php
Labels: good first issue

#53 Migration Result Paging test
  tests-old/features/result_paging.feature
  tests/Feature/Results/ResultPagingTest.php
Labels: enhancement
